### PR TITLE
add a note about alternative view layers

### PR DESCRIPTION
**Pull request by yyx990803**
screen shot 2015-07-21 at 1 27 04 pm

The Angular and React links link to the respective tutorials.

### CODE REVIEW

**Comment by stubailo** [comment]
Looks awesome. Can't wait until we can deploy these.

**Comment by lazaridis-com** [comment]
@stubailo @abernix - I guess this didn't made it into the repo. As a newcomer to the JS domain, my assessment is:

* Newcomers should be pointed to a Blaze tutorial (this would have made things much easier for me)
* The additional 2 tutorials should be presented as "advanced"
* This should be kept this way until MDG decides to use another UI layer as its default.

In any way, this PR is near 2 years old, and should be either applied or closed.

**Comment by lazaridis-com** [comment]
This should be closed (see #111)

**Comment by abernix** [comment]
In regards to the issue, the multiple view layer options are now presented on [the initial Tutorial page](https://www.meteor.com/tutorials) and this was an original goal of this issue and was completed after this issue was opened.

Agree to close.  Thanks, @lazaridis-com.

**Pull request closed without merging**
